orders:
  id: int(10) primary key
  number: varchar(20)
  item_total: float(10)
  total: float(10)
  ship_total: float(10)
  state: varchar(20)
  adjustment_total: float(10)
  user_id: varchar(20)
  created_at: varchar(30)
  updated_at: varchar(30)
  completed_at: varchar(30)
  payment_total: float(10)
  shipment_state: varchar(20)
  payment_state: varchar(20)
  email: varchar(30)
  special_instructions: varchar(30)
  channel: varchar(20)
  included_tax_total: float(10)
  additional_tax_total: float(10)
  display_included_tax_total: varchar(20)
  display_additional_tax_total: varchar(20)
  currency: varchar(5)
  display_item_total: varchar(20)
  total_quantity: int(3)
  display_total: varchar(20)
  display_ship_total: varchar(20)
  display_tax_total: varchar(20)
  token: varchar(30)
  checkout_steps: varchar(70)
